# Generated by Django 3.0.6 on 2020-05-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaarinfo',
            name='aadhaar_id',
            field=models.IntegerField(default=0),
        ),
    ]
