# Generated by Django 3.0.6 on 2020-05-13 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_management_system', '0003_liquor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='liquor_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='liquor_management_system.Liquor'),
            preserve_default=False,
        ),
    ]
