# Generated by Django 3.0.6 on 2020-05-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_management_system', '0004_transaction_liquor_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='liquor_info',
        ),
    ]
