# Generated by Django 3.0.6 on 2020-05-13 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_management_system', '0007_auto_20200513_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquor',
            name='liquor_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='liquor_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquor_management_system.Liquor'),
        ),
    ]
