# Generated by Django 3.0.6 on 2020-05-13 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_management_system', '0008_auto_20200513_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='liquor_info',
        ),
        migrations.DeleteModel(
            name='Liquor',
        ),
    ]
