# Generated by Django 3.0.6 on 2020-05-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_management_system', '0009_auto_20200513_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquor_name', models.CharField(max_length=100)),
                ('liquor_quantity', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='liquor_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='liquor_management_system.Liquor'),
            preserve_default=False,
        ),
    ]
