# Generated by Django 3.0.6 on 2020-05-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_management_system', '0012_auto_20200513_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
