# Generated by Django 3.0.6 on 2020-05-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_management_system', '0013_delete_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AadhaarInfo',
        ),
        migrations.DeleteModel(
            name='Liquor',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
