# Generated by Django 3.0.6 on 2020-05-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_management_system', '0015_aadhaarinfo_liquor_state_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquor',
            name='liquor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='liquor',
            name='liquor_quantity',
            field=models.FloatField(null=True),
        ),
    ]
