# Generated by Django 3.0.6 on 2020-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_management_system', '0017_auto_20200513_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquor',
            name='liquor_name',
            field=models.CharField(max_length=100),
        ),
    ]
