# Generated by Django 3.0.6 on 2020-05-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_management_system', '0018_auto_20200513_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='liquor_info',
        ),
    ]
