# Generated by Django 3.0.6 on 2020-05-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquor_management_system', '0021_auto_20200514_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='liquor_info',
        ),
    ]
